spring.application.name=hospital_manager


# config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_manager?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# config jpa
spring.jpa.show-sql=true
# chuaw co table thi tao ra hoac update neu field sai
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# sql sinh ra
spring.jpa.properties.hibernate.format_sql=true